---
# tasks file for Avorion Dedicated server
# This can have a notify: event and then be put at the end of the task list
- name: Add Avorion to firewalld services
  template:
    src: "{{ firewall_j2 }}"
    dest: /etc/firewalld/services/avorion.xml
    mode: 0644

# this can be put in the handler file
- name: reload firewalld
  systemd: 
    name: firewalld
    state: reloaded

# this can also be put in the handler file
- name: Start & Enable Avorion Firewalld service
  firewalld:
    service: avorion
    permanent: yes
    immediate: yes
    state: enabled

- name: create {{ vars.user }} user
  user: 
    name: "{{ vars.user }}"
    state: present

- name: Create some folders
  file:
    path: '/home/{{ user }}/{{ item }}'
    recurse: yes
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
  with_items: 
    - '{{ folders }}'

- name: install dependencies for steamcmd
  dnf:
    name: '{{ req_packages }}'
    state: present

- name: fetch and extract steamcmd
  unarchive:
    src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
    dest: /home/{{ vars.user }}/steamcmd
    remote_src: yes
    creates: '/home/{{ vars.user }}/steamcmd/steamcmd.sh'

- name: fix permissions of steamcmd
  file:
    path: '/home/{{ vars.user }}/steamcmd/'
    state: directory
    recurse: yes
    owner: steam
    group: steam

- name: install avorion into desired directory
  command: '/home/{{ vars.user }}/steamcmd/steamcmd.sh +login anonymous +force_install_dir /home/{{ vars.user }}/avorion +app_update 565060 validate +exit'
  become_user: '{{ vars.user }}'
  args:
    creates: '/home/{{ vars.user }}/avorion/server.sh'

- name: Copy/unarchive galaxy *.tar.gz archives to /home/{{ vars.user }}/avorion/galaxies
  unarchive:
    src: "{{ item }}"
    dest: '/home/{{ vars.user }}/avorion/galaxies'
    owner: '{{ vars.user }}'
    group: '{{ vars.user }}'
  with_fileglob:
    - '{{ vars.galaxies }}'


